### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError:indices[29,32]=1 is not in [0,1)

### ISSUE THREAD

**Issue by hesilan-1** [cloudyskyy/Guwen-UNILM#4]

**Comment by hesilan-1** [comment]
How can i resolve this problem?

**Comment by cloudyskyy** [comment]
Can you provide more detailed information of this error? Such as the environment of your code, the training data, and where the error happened.

**Comment by hesilan-1** [comment]
environment:
driver 460.67
cuda11.0
pip install tensorflow-gpu==1.15
pip install keras==2.3.1
pip install bert4keras==0.11.1
pip install h5py==2.10.0  


data:the same as you

position:
Epoch 1/15
Traceback (most recent call last):
  File "/home/zuo/Guwen-UNILM-main/train.py", line 178, in <module>
    callbacks=[evaluator]
  File "/home/zuo/anaconda3/envs/guwen/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/zuo/anaconda3/envs/guwen/lib/python3.7/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/zuo/anaconda3/envs/guwen/lib/python3.7/site-packages/keras/engine/training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "/home/zuo/anaconda3/envs/guwen/lib/python3.7/site-packages/keras/engine/training.py", line 1514, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/zuo/anaconda3/envs/guwen/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "/home/zuo/anaconda3/envs/guwen/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[29,37] = 1 is not in [0, 1)
	 [[{{node Embedding-Segment/embedding_lookup}}]]

Process finished with exit code 1




I downloaded /pretrained_models/guwenbert-base-tf  this repository.But there is no /roberta.ckpt   file in it.I think maybe this problem.

**Comment by hesilan-1** [comment]
May I have lucky to look your paper?I'll so much appreciate it!!!Because i can't download it from the google ~wuwuuw...My mail box is 1053604021@qq.com.Thank you so much!!!!(笔芯)

**Comment by cloudyskyy** [comment]
Alright, please kindly noted to check your mail ^_^

**Comment by JiaxinQin0814** [comment]
oh I have the same problem...

**Comment by JiaxinQin0814** [comment]
excuse me?have you solved this problem
